language: node_js
node_js:
  - "8"
deploy:
  - provider: script
    skip_cleanup: true
    script: 'git fetch --unshallow && npm run deploy'
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    local-dir: deploy
    repo: romainmeunier/openapi-directory
    github-token: $GH_DEPLOY_TOKEN
    keep-history: false
    on:
      branch: master

