swagger: '2.0'
schemes:
  - http
  - https
host: api.fantasydata.net
basePath: /v3/mlb/projections-dfsr
info:
  contact:
    x-twitter: nfldata
  description: MLB projections API from DailyFantasySportsRankings.com.
  title: MLB v3 Projections DFSR
  version: '1.0'
  x-apisguru-categories:
    - entertainment
  x-logo:
    url: 'https://twitter.com/nfldata/profile_image?size=original'
  x-origin:
    - format: swagger
      url: 'https://fantasydata.com/downloads/swagger/mlb-v3-projections-dfsr.json'
      version: '2.0'
  x-preferred: true
  x-providerName: fantasydata.net
  x-serviceName: mlb-v3-projections-dfsr
produces:
  - application/json
securityDefinitions:
  apiKeyHeader:
    in: header
    name: Ocp-Apim-Subscription-Key
    type: apiKey
  apiKeyQuery:
    in: query
    name: subscription-key
    type: apiKey
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
paths:
  '/{format}/DfsrPlayerGameProjectionStatsByDate/{date}':
    get:
      operationId: ProjectedPlayerGameStatsByDateWInjuriesLineupsDfsSalaries
      parameters:
        - default: XML
          description: Desired response format. Valid entries are <code>XML</code> or <code>JSON</code>.
          enum:
            - XML
            - JSON
          in: path
          name: format
          required: true
          type: string
        - description: |-
            The date of the game(s).
            <br>Examples: <code>2017-JUL-31</code>, <code>2017-SEP-01</code>.
          in: path
          name: date
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            items:
              $ref: '#/definitions/PlayerGameProjection'
            type: array
      summary: 'Projected Player Game Stats by Date (w/ Injuries, Lineups, DFS Salaries)'
  '/{format}/DfsrPlayerGameProjectionStatsByPlayer/{date}/{playerid}':
    get:
      operationId: ProjectedPlayerGameStatsByPlayerWInjuriesLineupsDfsSalaries
      parameters:
        - default: XML
          description: Desired response format. Valid entries are <code>XML</code> or <code>JSON</code>.
          enum:
            - XML
            - JSON
          in: path
          name: format
          required: true
          type: string
        - description: |-
            The date of the game(s).
            <br>Examples: <code>2017-JUL-31</code>, <code>2017-SEP-01</code>.
          in: path
          name: date
          required: true
          type: string
        - description: |-
            Unique FantasyData Player ID.
            Example:<code>10000507</code>.
          in: path
          name: playerid
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            items:
              $ref: '#/definitions/PlayerGameProjection'
            type: array
      summary: 'Projected Player Game Stats by Player (w/ Injuries, Lineups, DFS Salaries)'
definitions:
  PlayerGameProjection:
    properties:
      AtBats:
        type: number
      BallsInPlay:
        type: number
      BattingAverage:
        type: number
      BattingAverageOnBallsInPlay:
        type: number
      BattingOrder:
        type: integer
      BattingOrderConfirmed:
        type: boolean
      CaughtStealing:
        type: number
      DateTime:
        type: string
      Day:
        type: string
      DoublePlays:
        type: number
      Doubles:
        type: number
      DraftKingsPosition:
        type: string
      DraftKingsSalary:
        type: integer
      EarnedRunAverage:
        type: number
      Errors:
        type: number
      FanDuelPosition:
        type: string
      FanDuelSalary:
        type: integer
      FantasyDataSalary:
        type: integer
      FantasyDraftPosition:
        type: string
      FantasyDraftSalary:
        type: integer
      FantasyPoints:
        type: number
      FantasyPointsDraftKings:
        type: number
      FantasyPointsFanDuel:
        type: number
      FantasyPointsFantasyDraft:
        type: number
      FantasyPointsYahoo:
        type: number
      FieldingIndependentPitching:
        type: number
      FlyOuts:
        type: number
      GameID:
        type: integer
      Games:
        type: integer
      GlobalGameID:
        type: integer
      GlobalOpponentID:
        type: integer
      GlobalTeamID:
        type: integer
      GrandSlams:
        type: number
      GroundIntoDoublePlay:
        type: number
      GroundOuts:
        type: number
      HitByPitch:
        type: number
      Hits:
        type: number
      HomeOrAway:
        type: string
      HomeRuns:
        type: number
      InjuryBodyPart:
        type: string
      InjuryNotes:
        type: string
      InjuryStartDate:
        type: string
      InjuryStatus:
        type: string
      InningsPitchedDecimal:
        type: number
      InningsPitchedFull:
        type: number
      InningsPitchedOuts:
        type: number
      IntentionalWalks:
        type: number
      IsGameOver:
        type: boolean
      IsolatedPower:
        type: number
      LeftOnBase:
        type: number
      LineOuts:
        type: number
      Losses:
        type: number
      Name:
        type: string
      OnBasePercentage:
        type: number
      OnBasePlusSlugging:
        type: number
      Opponent:
        type: string
      OpponentID:
        type: integer
      OpponentPositionRank:
        type: integer
      OpponentRank:
        type: integer
      Outs:
        type: number
      PitchesSeen:
        type: number
      PitchesThrown:
        type: number
      PitchesThrownStrikes:
        type: number
      PitchingBallsInPlay:
        type: number
      PitchingBattingAverageAgainst:
        type: number
      PitchingBattingAverageOnBallsInPlay:
        type: number
      PitchingBlownSaves:
        type: number
      PitchingCatchersInterference:
        type: number
      PitchingCompleteGames:
        type: number
      PitchingDoublePlays:
        type: number
      PitchingDoubles:
        type: number
      PitchingEarnedRuns:
        type: number
      PitchingFlyOuts:
        type: number
      PitchingGrandSlams:
        type: number
      PitchingGroundIntoDoublePlay:
        type: number
      PitchingGroundOuts:
        type: number
      PitchingHitByPitch:
        type: number
      PitchingHits:
        type: number
      PitchingHolds:
        type: number
      PitchingHomeRuns:
        type: number
      PitchingInningStarted:
        type: integer
      PitchingIntentionalWalks:
        type: number
      PitchingLineOuts:
        type: number
      PitchingNoHitters:
        type: number
      PitchingOnBasePercentage:
        type: number
      PitchingOnBasePlusSlugging:
        type: number
      PitchingPerfectGames:
        type: number
      PitchingPlateAppearances:
        type: number
      PitchingPopOuts:
        type: number
      PitchingQualityStarts:
        type: number
      PitchingReachedOnError:
        type: number
      PitchingRuns:
        type: number
      PitchingSacrificeFlies:
        type: number
      PitchingSacrifices:
        type: number
      PitchingShutOuts:
        type: number
      PitchingSingles:
        type: number
      PitchingSluggingPercentage:
        type: number
      PitchingStrikeouts:
        type: number
      PitchingStrikeoutsPerNineInnings:
        type: number
      PitchingTotalBases:
        type: number
      PitchingTriples:
        type: number
      PitchingWalks:
        type: number
      PitchingWalksPerNineInnings:
        type: number
      PitchingWeightedOnBasePercentage:
        type: number
      PlateAppearances:
        type: number
      PlayerID:
        type: integer
      PopOuts:
        type: number
      Position:
        type: string
      PositionCategory:
        type: string
      ReachedOnError:
        type: number
      Runs:
        type: number
      RunsBattedIn:
        type: number
      SacrificeFlies:
        type: number
      Sacrifices:
        type: number
      Saves:
        type: number
      Season:
        type: integer
      SeasonType:
        type: integer
      Singles:
        type: number
      SluggingPercentage:
        type: number
      Started:
        type: integer
      StatID:
        type: integer
      StolenBases:
        type: number
      Strikeouts:
        type: number
      SubstituteBattingOrder:
        type: integer
      SubstituteBattingOrderSequence:
        type: integer
      Team:
        type: string
      TeamID:
        type: integer
      TotalBases:
        type: number
      TotalOutsPitched:
        type: number
      Triples:
        type: number
      Updated:
        type: string
      Walks:
        type: number
      WalksHitsPerInningsPitched:
        type: number
      WeightedOnBasePercentage:
        type: number
      Wins:
        type: number
      YahooPosition:
        type: string
      YahooSalary:
        type: integer
